FROM ubuntu:25.04

RUN apt-get update \
    && apt-get install -y lua5.1 luarocks neovim git \
    && luarocks install nlua \
    && luarocks install busted

RUN mkdir /app /appdata

WORKDIR /app

COPY slurp.nvim-scm-1.rockspec .busted .
COPY plugin/ plugin/
COPY lua/ lua/
COPY spec/ spec/
COPY src/spec/init.vim spec/init.vim
COPY --chmod=744 nluarocks/init ./nluarocks/init

