#!/usr/bin/env bash
#
# Run tests

set -euo pipefail

here=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
root=$(dirname $here)
. $here/env

path="${LUA_PATH:-};$1"
LUA_PATH=$path nvim --headless -c "PlenaryBustedDirectory $root/spec/"

